### ISSUE TITLE
AttributeError: 'FAISS' object has no attribute 'get_document_by_metadata'

### ISSUE THREAD

**Issue by mlDaddy** [yaacoo/graphRagSqlator#1]
Hi,
I am trying to set up your repo. However, it gives following error.

graphRagSqlator/graph_rag.py", line 149, in get_context
    context += f"  Common values: {self.vector_store.get_document_by_metadata('db', related_table.split('.')[0], 'table', related_table.split('.')[1]).page_content}\n"
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'FAISS' object has no attribute 'get_document_by_metadata'

I am using conda with python 3.11.5 and pip package version given in requirements.txt.

**Comment by yaacoo** [comment]
> Hi, I am trying to set up your repo. However, it gives following error.
> 
> graphRagSqlator/graph_rag.py", line 149, in get_context context += f" Common values: {self.vector_store.get_document_by_metadata('db', related_table.split('.')[0], 'table', related_table.split('.')[1]).page_content}\n" ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ AttributeError: 'FAISS' object has no attribute 'get_document_by_metadata'
> 
> I am using conda with python 3.11.5 and pip package version given in requirements.txt.

Thanks, I just pushed an update that should have solved it, please let me know. Instead of querying FAISS for each related node, extracting the information from the graph. It should also be more efficient than querying FAISS by metadata (instead of similarity) for every edge.
